## Linear Algebra for Machine Learning

The study of linear algebra involves several types of mathematical objects.  
1. Scalars   
2. Vectors 
3. Matrix  
4. Tensors

#### Scalras

#### Vectors

A vector is a 1-dimensional array of numbers. It has both magnitude and direction.  

In [10]:
import numpy as np

x = np.array([-2,0.4,2])
x

array([-2. ,  0.4,  2. ])

> A vector with n entries is an n-dimensional vector space.  

#### A feature vector is vector whose entries represent the features of some object.

#### Matirces 

A matrix is a 2-D array of numbers.  

> Python doesn't have a built-in type for matrices. However we can create using list of list. OR using `numpy` array.

For example

In [6]:
A = [[1,4,6],
    [-5,7,2]]
A

[[1, 4, 6], [-5, 7, 2]]

In [7]:
A[1][2]

2

In [13]:
A = np.array([[2, 4], [5, -6]])
print(A)

[[ 2  4]
 [ 5 -6]]


In [15]:
A.shape

(2, 2)

#### Tensors  

Array with more than two axes.


In [16]:
A = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [17]:
A.shape

(3, 3, 3)

### Operations


#### Transpose of matrix  

Transpose of matrix is the mirror image of the matrix across the diagonal line, called the **main diagonal**.


In [21]:
A = np.array([[2, 4, 4], [5, -6, 6]])
print(A)

[[ 2  4  4]
 [ 5 -6  6]]


In [22]:
A.T

array([[ 2,  5],
       [ 4, -6],
       [ 4,  6]])

Transpose of a vector 
$$ 
x = [x1, x2, x2]^T
$$ 

#### Addition of Matrix

In [24]:

A = np.array([[2, 4], [5, -6]])

B = np.array([[9, -2], [3,6]])

print(A)
print(B)

[[ 2  4]
 [ 5 -6]]
[[ 9 -2]
 [ 3  6]]


In [25]:
C = A + B
print(C)

[[11  2]
 [ 8  0]]


#### Multiplying Matrices and Vectors

The multiplication of two matrices ***A*** and ***B*** is a third matrix ***C***.

> For multiplication ***A*** should have same number of columns as  rows of matrix ***B***.

$$
C = AB
$$

In [26]:
A

array([[ 2,  4],
       [ 5, -6]])

In [27]:
B

array([[ 9, -2],
       [ 3,  6]])

In [29]:
# element wise product  or Hardamard product 
A*B

array([[ 18,  -8],
       [ 15, -36]])

#### Dot product of vectors

$$
dotproduct(x,y) = x^Ty
$$

> Dot product is nice way to measure similarity between vectors. (How?)

In [37]:
#Dot product

a = np.array([3,5])
b = np.array([7,2])


np.sum((a.T)*b)

31

In [38]:
#using @ notation
a@b

31

#### Intuition of dot product
The dot product represent the length of the shadow of one vector along another.

Matrix mulitplication ***C=AB***  as the dot product between row i of A and column j of B.

In [42]:
A = np.array([[1,3],
              [2,4]])

B = np.array([[4,2],
              [6, 3]])

In [43]:
np.dot(A,B)

array([[22, 11],
       [32, 16]])

In [44]:
A@B

array([[22, 11],
       [32, 16]])

#### properties of Matrix product operations

* Distributive Property
$$
A(B+C) = AB + BC
$$

* Associative Property

$$
A(BC) = (AB)C
$$


> Matrix multiplicatio is not  commutative. Hence ***AB = BA*** does not alwayshold.

* However dot product of two vectors is commutative.

$$
x^Ty = y^Tx
$$

The transpose of matrix has simple form.

$$
(AB)^T = B^TA^T
$$




#### System of linear equation

$$
Ax = b
$$

it simply 

$$
A_1,_1x_1 + A_1,_2x_2+...+A_1,_nx_n = b_1  
$$
$$
A_2,_1x_1 + A_2,_2x_2+...+A_2,_nx_n = b_2  
$$
$$
A_m,_1x_1 + A_m,_2x_2+...+A_m,_nx_n = b_m 
$$



#### Identity and Inverse Matrices

Linear algebra provides us a very powerful tool which is called as matrix inversion. This help us solving equation ***Ax = B*** analytically.  

To describe matrix inversion we need to understand **Identity matrix** first.

> An identity matrix is a matrix that does not change any vector when we multiply that vector by that matrix.  


$$
I_nx = x
$$

In [56]:
# identity matrix
A = np.identity(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
B = np.random.randn(3,3)
B

array([[-4.49665423e-02,  1.44375889e+00, -7.82236379e-02],
       [-9.10560399e-01,  1.39720359e+00,  5.80557087e-01],
       [-2.36578505e-04,  1.19298659e-01,  9.04411651e-01]])

In [61]:
#matrix multiplication
A@B

array([[-4.49665423e-02,  1.44375889e+00, -7.82236379e-02],
       [-9.10560399e-01,  1.39720359e+00,  5.80557087e-01],
       [-2.36578505e-04,  1.19298659e-01,  9.04411651e-01]])

Matrix Inverse of ***A*** is denoted as ***A_-1*** and it is defined as :  

$$
A^{-1}A = I_n
$$


Now we can solve the System of linear equation as :  
$$
Ax = B
$$
$$
A^{-1}Ax = A^{-1}b
$$
$$
I_nx = A^{-1}b
$$
$$
x = A^{-1}b
$$

This process depends on its being possible to find $A^{-1}$